version: '3.8'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8082:8080"  # Porta para o Camunda
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - CAMUNDA_JDBC_URL=jdbc:postgresql://db:5432/camunda
    depends_on:
      - db

  cockpit:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - "8083:8080"  # Porta para o Cockpit
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    ports:
      - "5434:5432"  # Porta para acessar o PostgreSQL se necessário
