version: '3.8'

services:
  db:
    image: postgres:14
    container_name: gothamcity-db
    environment:
      POSTGRES_DB: gothamcity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Expor o PostgreSQL na porta 5433 no host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
